name: Mark PRs as deployed

on:
    push:
        branches: [master]

jobs:
    write-comments:
        runs-on: ubuntu-latest
        steps:
            - name: Mark Pull Requests as Deployed
              uses: mikeattara/mark-prs-as-deployed@v1.6
              with:
                  PR_LIST: '[11, 12, 13]'
                  IS_PRODUCTION_DEPLOY: 'true'




