name: Mark PRs as deployed

on:
    push:
        branches: [master]

jobs:
    write-comments:
        runs-on: ubuntu-latest
        steps:
            - name: Mark Pull Requests as Deployed
              uses: mikeattara/mark-prs-as-deployed@v1.5.4
              with:
                  PR_LIST: '[7, 8, 9, 10]'
                  IS_PRODUCTION_DEPLOY: 'true'




